import type { TaskTemplate } from '../types/task-template'
import { PatientStatus, TaskCategory, SurgeryPhase, HolidayRule } from '../types/enums'

export const seedTaskTemplates: TaskTemplate[] = [
  // ========== 入院当日 (day0) ==========
  { key: 'day0_admission_record', title: '写入院记录', patientStatus: PatientStatus.DAY0_ADMISSION, category: TaskCategory.MEDICAL_RECORD, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: 0, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 1, isActive: true, isOnceOnly: false },
  { key: 'day0_first_course', title: '写首程', patientStatus: PatientStatus.DAY0_ADMISSION, category: TaskCategory.MEDICAL_RECORD, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: 0, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 2, isActive: true, isOnceOnly: false },
  { key: 'day0_attending_rounds', title: '写主治查房', patientStatus: PatientStatus.DAY0_ADMISSION, category: TaskCategory.MEDICAL_RECORD, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: 0, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 3, isActive: true, isOnceOnly: false },
  { key: 'day0_deputy_director', title: '写副主任查房', description: '假期前一天入院加写', patientStatus: PatientStatus.DAY0_ADMISSION, category: TaskCategory.MEDICAL_RECORD, weekday: null, surgeryPhase: null, isHolidayDependent: true, holidayRule: HolidayRule.BEFORE_HOLIDAY, dayOffsetFromAdmission: 0, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 4, isActive: true, isOnceOnly: false },
  { key: 'day0_order', title: '开医嘱', patientStatus: PatientStatus.DAY0_ADMISSION, category: TaskCategory.ORDER, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: 0, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 5, isActive: true, isOnceOnly: false },
  { key: 'day0_print', title: '打印检查单、调药单', patientStatus: PatientStatus.DAY0_ADMISSION, category: TaskCategory.PRINT, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: 0, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 6, isActive: true, isOnceOnly: false },
  { key: 'day0_sign', title: '签字', patientStatus: PatientStatus.DAY0_ADMISSION, category: TaskCategory.SIGN, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: 0, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 7, isActive: true, isOnceOnly: false },
  { key: 'day0_ecg', title: '做心电图', patientStatus: PatientStatus.DAY0_ADMISSION, category: TaskCategory.ECG, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: 0, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 8, isActive: true, isOnceOnly: false },
  { key: 'day0_ecg_report', title: '出心电图报告', patientStatus: PatientStatus.DAY0_ADMISSION, category: TaskCategory.ECG, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: 0, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 9, isActive: true, isOnceOnly: false },

  // ========== 入院第二日 (day1) ==========
  { key: 'day1_deputy_director', title: '写副主任查房', patientStatus: PatientStatus.DAY1_ADMISSION, category: TaskCategory.MEDICAL_RECORD, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: 1, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 1, isActive: true, isOnceOnly: false },
  { key: 'day1_daily_record', title: '写日常病程', description: '周六日写', patientStatus: PatientStatus.DAY1_ADMISSION, category: TaskCategory.MEDICAL_RECORD, weekday: null, surgeryPhase: null, isHolidayDependent: true, holidayRule: HolidayRule.NON_WORKDAY, dayOffsetFromAdmission: 1, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 1, isActive: true, isOnceOnly: false },

  // ========== 在院正常 (normal_inpatient) - 按星期几 ==========
  { key: 'normal_mon', title: '写主治查房病程', patientStatus: PatientStatus.NORMAL_INPATIENT, category: TaskCategory.MEDICAL_RECORD, weekday: 1, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 1, isActive: true, isOnceOnly: false },
  { key: 'normal_tue', title: '写主治查房病程', patientStatus: PatientStatus.NORMAL_INPATIENT, category: TaskCategory.MEDICAL_RECORD, weekday: 2, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 1, isActive: true, isOnceOnly: false },
  { key: 'normal_wed', title: '写主任查房病程', patientStatus: PatientStatus.NORMAL_INPATIENT, category: TaskCategory.MEDICAL_RECORD, weekday: 3, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 1, isActive: true, isOnceOnly: false },
  { key: 'normal_thu', title: '写主治查房病程', patientStatus: PatientStatus.NORMAL_INPATIENT, category: TaskCategory.MEDICAL_RECORD, weekday: 4, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 1, isActive: true, isOnceOnly: false },
  { key: 'normal_fri', title: '写副主任查房病程', patientStatus: PatientStatus.NORMAL_INPATIENT, category: TaskCategory.MEDICAL_RECORD, weekday: 5, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 1, isActive: true, isOnceOnly: false },
  { key: 'day3_weekend_record', title: '写日常病程', description: '入院第三天，非工作日', patientStatus: PatientStatus.NORMAL_INPATIENT, category: TaskCategory.MEDICAL_RECORD, weekday: null, surgeryPhase: null, isHolidayDependent: true, holidayRule: HolidayRule.NON_WORKDAY, dayOffsetFromAdmission: 3, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 1, isActive: true, isOnceOnly: false },

  // ========== 术前准备期 (surgery_pre) — 一次性任务 ==========
  { key: 'surgery_sign_consent', title: '签手术相关知情同意书', patientStatus: PatientStatus.SURGERY_PRE, category: TaskCategory.SIGN, weekday: null, surgeryPhase: SurgeryPhase.ANY_TIME, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 1, isActive: true, isOnceOnly: true },
  { key: 'surgery_sign_self_pay', title: '签自费知情', patientStatus: PatientStatus.SURGERY_PRE, category: TaskCategory.SIGN, weekday: null, surgeryPhase: SurgeryPhase.ANY_TIME, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 2, isActive: true, isOnceOnly: true },
  { key: 'surgery_antiplatelet', title: '开双联抗血小板医嘱', description: '必要时加用护胃药物', patientStatus: PatientStatus.SURGERY_PRE, category: TaskCategory.ORDER, weekday: null, surgeryPhase: SurgeryPhase.ANY_TIME, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 3, isActive: true, isOnceOnly: true },

  // ========== 术前一天 (pre_surgery) ==========
  { key: 'surgery_pre_order', title: '开术前医嘱', patientStatus: PatientStatus.PRE_SURGERY, category: TaskCategory.ORDER, weekday: null, surgeryPhase: SurgeryPhase.PRE_DAY, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: -1, dayOffsetFromDischarge: null, order: 1, isActive: true, isOnceOnly: false },
  { key: 'surgery_pre_discuss', title: '完成术前讨论文书', patientStatus: PatientStatus.PRE_SURGERY, category: TaskCategory.MEDICAL_RECORD, weekday: null, surgeryPhase: SurgeryPhase.PRE_DAY, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: -1, dayOffsetFromDischarge: null, order: 2, isActive: true, isOnceOnly: false },

  // ========== 手术当日 (surgery_day) ==========
  { key: 'surgery_day_vitals', title: '松夹子、测血压、做心电图', patientStatus: PatientStatus.SURGERY_DAY, category: TaskCategory.ECG, weekday: null, surgeryPhase: SurgeryPhase.SURGERY_DAY, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: 0, dayOffsetFromDischarge: null, order: 1, isActive: true, isOnceOnly: false },
  { key: 'surgery_day_post', title: '看术后回单，开相关检查', patientStatus: PatientStatus.SURGERY_DAY, category: TaskCategory.ORDER, weekday: null, surgeryPhase: SurgeryPhase.SURGERY_DAY, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: 0, dayOffsetFromDischarge: null, order: 2, isActive: true, isOnceOnly: false },
  { key: 'surgery_day_post_course', title: '写术后首程', patientStatus: PatientStatus.SURGERY_DAY, category: TaskCategory.MEDICAL_RECORD, weekday: null, surgeryPhase: SurgeryPhase.SURGERY_DAY, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: 0, dayOffsetFromDischarge: null, order: 3, isActive: true, isOnceOnly: false },

  // ========== 术后恢复 (post_surgery) — 术后第1-2天 ==========
  { key: 'post_surgery_record', title: '写术后病程', description: '手术后3日内每日需有病程', patientStatus: PatientStatus.POST_SURGERY, category: TaskCategory.MEDICAL_RECORD, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: null, order: 1, isActive: true, isOnceOnly: false },

  // ========== 预出院 (pre_discharge) ==========
  { key: 'predischarge_order', title: '开预出院医嘱', description: '明日出院/隔一日出院/隔两日出院', patientStatus: PatientStatus.PRE_DISCHARGE, category: TaskCategory.ORDER, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: -1, order: 1, isActive: true, isOnceOnly: false },
  { key: 'predischarge_med', title: '开出院带药医嘱', patientStatus: PatientStatus.PRE_DISCHARGE, category: TaskCategory.ORDER, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: -1, order: 2, isActive: true, isOnceOnly: false },
  { key: 'predischarge_cert', title: '写出院诊断证明书', patientStatus: PatientStatus.PRE_DISCHARGE, category: TaskCategory.MEDICAL_RECORD, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: -1, order: 3, isActive: true, isOnceOnly: false },
  { key: 'predischarge_insurance', title: '审核医保', patientStatus: PatientStatus.PRE_DISCHARGE, category: TaskCategory.DISCHARGE, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: -1, order: 4, isActive: true, isOnceOnly: false },

  // ========== 出院当日 (discharge_day) ==========
  { key: 'discharge_order', title: '开今日出院，停长期医嘱', patientStatus: PatientStatus.DISCHARGE_DAY, category: TaskCategory.ORDER, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: 0, order: 1, isActive: true, isOnceOnly: false },
  { key: 'discharge_archive', title: '填写病案首页，归档病历', patientStatus: PatientStatus.DISCHARGE_DAY, category: TaskCategory.DISCHARGE, weekday: null, surgeryPhase: null, isHolidayDependent: false, holidayRule: null, dayOffsetFromAdmission: null, dayOffsetFromSurgery: null, dayOffsetFromDischarge: 0, order: 2, isActive: true, isOnceOnly: false },
]
